import { ProductItem } from '../data/schema/product';

export class ProductService {
  productList: ProductItem[] = [
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
    {
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
      imageGalleries: [
        'assets/images/product/product7.jpg',
        'assets/images/product/product6.jpg',
        'assets/images/product/product1.jpg',
        'assets/images/product/product2.jpg',
        'assets/images/product/product5.jpg',
        'assets/images/product/product8.jpg',
      ],
      description:
        'eget velit. Donec ac tempus ante. Fusce ultricies massa massa. Fusce aliquam, purus eget sagittis vulputate, sapien libero hendrerit est, sed commodo augue nisi non neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor, lorem et placerat vestibulum, metus nisi posuere nisl, in',
      customerRating: 5,
    },
  ];
}
