import { Component, OnInit } from '@angular/core';
import { ProductItem } from './product-section/product.model';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  productList: ProductItem[] = [
    {
      mainImage: 'assets/images/product/product7.jpg',
      secondImage: 'assets/images/product/product6.jpg',
      name: 'Aliquam Consequat',
      category: 'Fruits',
      currentPrice: '$26.00',
      oldPrice: '$362.00',
      isSale: true,
      isNew: true,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    },
    {
      mainImage: 'assets/images/product/product5.jpg',
      secondImage: 'assets/images/product/product8.jpg',
      name: 'Cas Meque Metus',
      category: 'Fruits',
      currentPrice: '$56.00',
      oldPrice: '$109.00',
      isSale: true,
      isNew: false,
    }
  ]
  constructor() { }

  ngOnInit(): void {
  }

}
